settings:
  database:
    host: 172.18.0.1
    port: 3306
    user: rpg-test
    password: jPGbpbpCy3W5Ssmz
    database: rpg-test
  dungeon:
    normal-display: "&f&l功能"
    team-display: "&f&l常规副本"
    activity-display: "&f&l困难副本"
    special-display: "&f&l特殊副本"