#         Powered by TabooLib 5.0         #


name: KirraZonesClient
main: ${main}
version: ${version}
authors: [ 'SakuraGames', '咸蛋' ]

depend:
  - JustMessage
  - LuckPerms
  - DungeonClient
  - DataManager
  - KirraCoreBukkit
  - KirraParty
  - Zaphkiel

lib-download: true
lib-version: ${libVersion}
loader-version: ${loaderVersion}
