settings:
  database:
    host: 172.18.0.1
    port: 3306
    user: rpg-test
    password: jPGbpbpCy3W5Ssmz
    database: rpg-test
  debug-mode: true
  delay-back-spawn-server-secs: 5
  death-notices:
    - "&c&l菜"
    - "&c&l?"
    - "&c&lYOUR DIED"
    - "&c&l死"
    - "&c&l你太弱了"